### ISSUE TITLE
Potential conflict with popup navigation & auto open popen using J and K keys

### ISSUE THREAD

**Issue by FunkySayu** [CharlesGueunet/vimmic#2]
Vimmic is configured to automatically open a popup window once he can (instead of using, for example, `<C-P>`)

```
" automatically open and close the popup menu / preview window
au CursorMovedI,InsertLeave * if pumvisible() == 0|silent! pclose|endif
```

However this configuration is mixed with the following one:

```
inoremap <expr> j ((pumvisible())?("\<C-n>"):("j"))
inoremap <expr> k ((pumvisible())?("\<C-p>"):("k")) 
```

Which allows the user to navigate with keys `j` and `k` in the popup window in insert mode.

This feature is interesting, but can be harmful in some cases. For example considere the following snippet:

``` go
const LOCK_SOMETHING = true

func MyFunc() {
    mystring := "I am using a loc|      <----- Vim cursor is here
```

A popen opens, which will suggest `LOCK_SOMETHING` while writing `loc`. By pressing `k`, I enter in the popup and choose the first occurence (i.e. `LOCK_SOMETHING`) which was not intended.

This behaviour might be harmful for vim begginers (like me!). My suggestion would be to put in the documentation the two `inoremap` lines and disable them by default.

**Comment by vollia** [comment]
Should be resolved now
