### ISSUE TITLE
Illegal values in Ale.vim config file for neovim

### ISSUE THREAD

**Issue by markhlang** [CharlesGueunet/vimmic#9]
I updated vimmic today since then neovim start with the following error message:

> Error detected while processing VimEnter Autocommands for "*":
> E418: Illegal value: red

Starting neovim in debug mode results in the following:
> autocommand highlight ALEVirtualTextError cterm=red cterm=bold
Press ENTER or type command to continue
Error detected while processing VimEnter Autocommands for "*":
E418: Illegal value: red
Press ENTER or type command to continue
autocommand highlight ALEVirtualTextWarning cterm=yellow cterm=bold
Press ENTER or type command to continue
Error detected while processing VimEnter Autocommands for "*":
E418: Illegal value: yellow
Press ENTER or type command to continue
autocommand highlight ALEVirtualTextIngo cterm=cyan cterm=bold
Press ENTER or type command to continue
Error detected while processing VimEnter Autocommands for "*":
E418: Illegal value: cyan

Searching in .vimmic it seems to be the lines 22 - 26 in the config file Ale.vim is the issue.

According to the [Nvim documentation](https://neovim.io/doc/user/usr_06.html) allowed values for cterm are "bold" and "underline". For colors ctermfg and/or ctermbg has to be used.

**Comment by vollia** [comment]
The last commit ab5fbf44044ff07001491e5a47f041948859929b should solve the issue.
I mistakenly used `cterm` instead of `ctermfg` and didn't notice as I use `termguicolors` in my config.

Thanks for reporting the issue :)

Charles

**Comment by markhlang** [comment]
Commit fixed the issue. Thank you. :)
